### ISSUE TITLE
Upload source code to repository

### ISSUE THREAD

**Issue by vinh-tranhuu** [210419-USF-BSN-Java/Rick-Ricci#1]
Hey Rick, make sure to upload your source code with your project structure to Github rather than a zip file

**Comment by RickRicci** [comment]
Howdy Kevin,



I have already done so; the source code w/ project structure is in the zip file. 

The zip does contain the entire project from my local eclipse-workspace.  



Regards,

-Rick







---- On Fri, 23 Apr 2021 16:49:33 -0400 vinh-tranhuu ***@***.***> wrote ----




Hey Rick, make sure to upload your source code with your project structure to Github rather than a zip file

**Comment by vinh-tranhuu** [comment]
In order to make it easily readable by other developers it's best practice to not package it before you upload it. Simply upload the file structure that you have as is
